[package]
name = "mcbe-rust-bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["tlhelp32", "memoryapi", "processthreadsapi", "synchapi", "handleapi", "winbase", "psapi"] }
ntapi = { version = "0.4", features = ["ntpsapi"] }